[tool.black]
target-version = ['py39']

[tool.isort]
# Black compat
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
# isort configuration
py_version = 'auto'
atomic = true
combine_as_imports = true
combine_star = true
force_sort_within_sections = true
order_by_type = true
float_to_top = true
skip_gitignore = true
